# Generated by Django 5.0.2 on 2024-02-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("published_by", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField()),
                ("image", models.ImageField(upload_to="book_images/")),
                ("desc", models.TextField()),
            ],
        ),
    ]
