# Generated by Django 5.0.2 on 2024-02-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("published_by", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField()),
                ("add_date", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(upload_to="book_images/")),
            ],
        ),
    ]
