# Generated by Django 5.0.2 on 2024-02-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_borrowbookmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowbookmodel",
            name="date_borrow",
            field=models.DateTimeField(),
        ),
    ]
