# Generated by Django 5.0.2 on 2024-02-15 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_borrowbookmodel_book"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowbookmodel",
            name="book",
        ),
        migrations.AddField(
            model_name="borrowbookmodel",
            name="book",
            field=models.ForeignKey(
                blank=True,
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.bookmodel",
            ),
            preserve_default=False,
        ),
    ]
