# Generated by Django 5.0.2 on 2024-02-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_remove_borrowbookmodel_book_borrowbookmodel_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowbookmodel",
            name="user_image",
            field=models.ImageField(upload_to="borrow_user_images/"),
        ),
    ]
